# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.13
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
      - id: trailing-whitespace
      - id: check-toml
      - id: end-of-file-fixer

  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   rev: v0.9.5
  #   hooks:
  #     - id: ruff
  #       args: [--fix, --exit-non-zero-on-fix]
  #       exclude: ^(pythonchik/main_original\.py|examples/.*)$
  #     - id: ruff-format
  #       exclude: ^(pythonchik/main_original\.py|examples/.*)$

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.8.0
  #   hooks:
  #     - id: mypy
  #       additional_dependencies:
  #         - types-Pillow
  #         - types-setuptools
  #         - types-toml
  #         - types-PyYAML
  #       exclude: ^(pythonchik/main_original\.py|examples/.*)$

  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.7.6
  #   hooks:
  #     - id: bandit
  #       args: [-ll]
  #       files: .py$
  #       exclude: ^(pythonchik/main_original\.py|examples/.*)$

  # - repo: https://github.com/psf/black
  #   rev: 24.8.0
  #   hooks:
  #     - id: black
  #       exclude: ^(pythonchik/main_original\.py|examples/.*)$
