# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.12
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
      - id: trailing-whitespace
      - id: check-toml
      - id: end-of-file-fixer

#  - repo: https://github.com/astral-sh/ruff-pre-commit
#    rev: v0.5.6
#    hooks:
#      - id: ruff
#        args: [--fix]
#      - id: ruff-format
#        exclude: ^(ammo.py|mypycodequality.py)

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
